id: P006996
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:35:02.294886
source_metadata:
  id: bdr:W8LS18982
  title: ཆོས་ཀྱི་ཤན་འབྱེད།
  author: ''
  volumes:
    6b707fd5befa45529932386acbec5a63:
      image_group_id: I8LS18984
      title: Volume 1 of chos kyi shan 'byed/ jo nang dpe tshogs/ 40
      volume_number: 1
      total_pages: 362
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
