id: P006996
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18982
  title: ཆོས་ཀྱི་ཤན་འབྱེད།
  author: ''
  volumes:
    27361dfa15e44d67bc19530d636252c4:
      image_group_id: I8LS18984
      title: ''
      volume_number: 1
      total_pages: 362
ebook_metadata:
  title: ཆོས་ཀྱི་ཤན་འབྱེད།
  author: ''
  sku: P006996
  cover: cover.jpg
  layers:
  - pagination
