id: I948A8774
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:39:08+00:00'
last_modified: '2022-06-08T10:55:22.016630+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18982
  title: ཆོས་ཀྱི་ཤན་འབྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7C13:
      image_group_id: I8LS18984
      title: Volume 1 of chos kyi shan 'byed/ jo nang dpe tshogs/ 40
      total_pages: 362
      order: 1
      base_file: 7C13.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
